#!/bin/bash
# /etc/init.d/raspicam-init

### BEGIN INIT INFO
# Provides:          servoblaster
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Example initscript
# Description:       This service is used to manage a servo
### END INIT INFO


case "$1" in 
    start)
        echo "Starting raspicam"
        /usr/local/bin/raspicam > /dev/null 2>&1 &
        ;;
    stop)
        echo "Stopping raspicam"
        killall raspicam
        ;;
    *)
        echo "Usage: /etc/init.d/raspicam-init start|stop"
        exit 1
        ;;
esac

exit 0
